"""
Generate the exponential decay look-up table for the STDP HLS kernel.

Produces two files (run from fpga_stdp/ directory):
  - exp_lut.coe          — BRAM initialisation file for Vivado IP
  - hls/exp_lut_init.h   — C float array included by stdp_top.cpp

Encoding: Q1.15 unsigned fixed-point
  integer = round(exp(-k * DT / TAU) * 32768)
  k = 0 → exp(0) = 1.0 → 32768
  k = 200 → exp(-1) ≈ 0.3679 → 12054
  k = 2047 → exp(-10.235) ≈ 0.0000358 → ~1
"""
import numpy as np
import os

TAU   = 20.0    # ms  (tau_plus = tau_minus in the Python sim)
DT    = 0.1     # ms  (simulation resolution)
N     = 2048    # LUT entries — covers 2047 × 0.1 = 204.7 ms ≈ 10 × TAU
SCALE = 32768   # Q1.15: 1.0 maps to 32768

entries = []
for k in range(N):
    val   = np.exp(-k * DT / TAU)
    fixed = int(round(val * SCALE))
    fixed = max(0, min(65535, fixed))
    entries.append(fixed)

# -------------------------------------------------------------------------
# Write COE file (for Vivado BRAM IP initialisation)
# -------------------------------------------------------------------------
coe_path = os.path.join(os.path.dirname(__file__), "..", "exp_lut.coe")
coe_path = os.path.normpath(coe_path)
with open(coe_path, "w") as f:
    f.write("memory_initialization_radix=16;\n")
    f.write("memory_initialization_vector=\n")
    for i, v in enumerate(entries):
        sep = "," if i < N - 1 else ";"
        f.write(f"{v:04x}{sep}\n")
print(f"Written: {coe_path}")

# -------------------------------------------------------------------------
# Write C header (included by stdp_top.cpp for HLS co-simulation)
# -------------------------------------------------------------------------
hdr_path = os.path.join(os.path.dirname(__file__), "..", "hls", "exp_lut_init.h")
hdr_path = os.path.normpath(hdr_path)
with open(hdr_path, "w") as f:
    f.write("// Auto-generated by gen_exp_lut.py — do not edit\n")
    f.write("// exp(-k * 0.1 / 20.0) for k = 0 .. 2047, encoded as Q1.15 float values\n")
    for i, v in enumerate(entries):
        val_float = v / SCALE
        sep = "," if i < N - 1 else ""
        f.write(f"    {val_float:.10f}{sep}\n")
print(f"Written: {hdr_path}")

# -------------------------------------------------------------------------
# Sanity checks
# -------------------------------------------------------------------------
print(f"\nSanity checks:")
print(f"  entries[0]    = {entries[0]}   (exp(0)=1.0   → should be 32768)")
print(f"  entries[200]  = {entries[200]}  (exp(-1)≈0.368 → should be ~12054)")
print(f"  entries[2047] = {entries[2047]}   (exp(-10.235) → should be near 0)")
assert entries[0] == 32768, "entries[0] must be 32768"
assert 12000 < entries[200] < 12100, f"entries[200] out of expected range: {entries[200]}"
print("All checks passed.")
